
-- 본사 상품관리 테이블 조회
SELECT 
    h.PRODUCT_NUM,
    bb.ITEM_NAME AS brand,
    b.ITEM_NAME,
    pp.COLOR AS color,
    p.COLOR AS prd_size,
    h.COST,
    h.REG_DATE,
    h.PRODUCT_COUNT
FROM HEAD_OFFICE_PRODUCT h
JOIN BRAND_ITEM b ON h.ITEM_NUM = b.ITEM_NUM
JOIN PRODUCT_PROPERTIES p ON h.PROPERTIES_NUM = p.PROPERTIES_NUM
LEFT JOIN PRODUCT_PROPERTIES pp ON p.REF_NUM = pp.PROPERTIES_NUM
LEFT JOIN BRAND_ITEM bb ON b.REF_NUM = bb.ITEM_NUM 
WHERE b.ITEM_NAME like '%'||''||'%';

SELECT * FROM head_office_product ORDER BY PRODUCT_NUM asc;
SELECT * FROM PRODUCT_PROPERTIES pp;
SELECT * FROM BRAND_ITEM bi;

CREATE SEQUENCE PRODUCT_NUM_SEQ START WITH 1 INCREMENT BY 1;
-- 블랙, 230 조던 범고래
INSERT INTO HEAD_OFFICE_PRODUCT (PRODUCT_NUM, PROPERTIES_NUM, ITEM_NUM, COST, REG_DATE, PRODUCT_COUNT)
VALUES (PRODUCT_NUM_SEQ.NEXTVAL, 101, 1001, 140000, TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'YYYY-MM-DD'), 0);
-- 레드, 260, 디파이올데이
INSERT INTO HEAD_OFFICE_PRODUCT (PRODUCT_NUM, PROPERTIES_NUM, ITEM_NUM, COST, REG_DATE, PRODUCT_COUNT)
VALUES (PRODUCT_NUM_SEQ.NEXTVAL, 204, 1005, 123000, TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'YYYY-MM-DD'), 0);



SELECT 
		    h.PRODUCT_NUM,
		    bb.ITEM_NAME AS brand,
		    b.ITEM_NAME,
		    pp.COLOR AS color,
		    p.COLOR AS prd_size,
		    h.COST,
		    h.REG_DATE,
		    h.PRODUCT_COUNT,
		    p.PROPERTIES_NUM,
		    b.ITEM_NUM
		FROM HEAD_OFFICE_PRODUCT h 
		JOIN BRAND_ITEM b ON h.ITEM_NUM = b.ITEM_NUM
		JOIN PRODUCT_PROPERTIES p ON h.PROPERTIES_NUM = p.PROPERTIES_NUM
		LEFT JOIN PRODUCT_PROPERTIES pp ON p.REF_NUM = pp.PROPERTIES_NUM
		LEFT JOIN BRAND_ITEM bb ON b.REF_NUM = bb.ITEM_NUM 
		WHERE b.ITEM_NAME like '%'||''||'%' ORDER BY PRODUCT_NUM ASC;


SELECT * FROM BRAND_ITEM bi 
WHERE REF_NUM = 0;
SELECT * FROM BRAND_ITEM bi 
WHERE REF_NUM = 1000;



SELECT DISTINCT pp.PROPERTIES_NUM, pp.COLOR, pp.REF_NUM
		FROM PRODUCT_PROPERTIES pp, PRODUCT_PROPERTIES pp2 
		WHERE pp.PROPERTIES_NUM LIKE '%%'
		AND pp.PROPERTIES_NUM = pp2.REF_NUM;

SELECT DISTINCT * FROM PRODUCT_PROPERTIES pp 
WHERE REF_NUM = 0;




SELECT DISTINCT HOP.PROPERTIES_NUM, PP.COLOR, bi.ITEM_NAME  
FROM HEAD_OFFICE_PRODUCT hop 
JOIN PRODUCT_PROPERTIES pp ON HOP.PROPERTIES_NUM = PP.PROPERTIES_NUM
JOIN BRAND_ITEM bi ON hop.ITEM_NUM = bi.ITEM_NUM 
WHERE PP.REF_NUM = '100'
AND bi.ITEM_NUM = '1001';






INSERT INTO PRODUCT_PROPERTIES pp VALUES (99, 220, 100);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (98, 210, 100);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (106, 280, 100);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (107, 290, 100);

SELECT DISTINCT * FROM PRODUCT_PROPERTIES pp 
	 ORDER BY PROPERTIES_NUM ASC; 

SELECT * FROM PRODUCT_PROPERTIES pp;

INSERT INTO PRODUCT_PROPERTIES pp VALUES (199, 220, 200);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (198, 210, 200);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (207, 290, 200);



INSERT INTO PRODUCT_PROPERTIES pp VALUES (300, '옐로', 0);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (301, 210, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (302, 220, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (303, 230, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (304, 240, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (305, 250, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (306, 260, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (307, 270, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (308, 280, 300);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (309, 290, 300);

INSERT INTO PRODUCT_PROPERTIES pp VALUES (400, '그레이', 0);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (401, 210, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (402, 220, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (403, 230, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (404, 240, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (405, 250, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (406, 260, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (407, 270, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (408, 280, 400);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (409, 290, 400);

INSERT INTO PRODUCT_PROPERTIES pp VALUES (500, '핑크', 0);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (501, 210, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (502, 220, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (503, 230, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (504, 240, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (505, 250, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (506, 260, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (507, 270, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (508, 280, 500);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (509, 290, 500);

INSERT INTO PRODUCT_PROPERTIES pp VALUES (600, '블루', 0);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (601, 210, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (602, 220, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (603, 230, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (604, 240, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (605, 250, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (606, 260, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (607, 270, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (608, 280, 600);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (609, 290, 600);

INSERT INTO PRODUCT_PROPERTIES pp VALUES (700, '그린', 0);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (701, 210, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (702, 220, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (703, 230, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (704, 240, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (705, 250, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (706, 260, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (707, 270, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (708, 280, 700);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (709, 290, 700);

INSERT INTO PRODUCT_PROPERTIES pp VALUES (800, '브라운', 0);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (801, 210, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (802, 220, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (803, 230, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (804, 240, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (805, 250, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (806, 260, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (807, 270, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (808, 280, 800);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (809, 290, 800);

INSERT INTO PRODUCT_PROPERTIES pp VALUES (900, '네이비', 0);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (901, 210, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (902, 220, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (903, 230, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (904, 240, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (905, 250, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (906, 260, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (907, 270, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (908, 280, 900);
INSERT INTO PRODUCT_PROPERTIES pp VALUES (909, 290, 900);








SELECT * FROM HEAD_OFFICE_PRODUCT hop;


UPDATE HEAD_OFFICE_PRODUCT SET PRODUCT_COUNT = #{product_num} WHERE PRODUCT_NUM = #{product_num};



SELECT * FROM head_office_product ORDER BY PRODUCT_NUM asc;

SELECT * FROM STORE_STORAGE ss WHERE STORE_NUM = 1 ORDER BY PRODUCT_NUM ASC;

UPDATE STORE_STORAGE SET STORAGE_COUNT = 12 WHERE STORE_NUM =1 AND PRODUCT_NUM  = 4;


















