CREATE SEQUENCE ORDER_seq;
DROP SEQUENCE ORDER_seq;

INSERT INTO ORDER_ERP values(TO_CHAR(SYSDATE,'YYYY/MM/DD')||'-'||ORDER_seq.NEXTVAL,1,23,sysdate,sysdate+(INTERVAL '7'day),1,0);

ALTER TABLE HIMAN.ORDER_ERP ADD textColor VARCHAR2(50);