SELECT 
    p.PRODUCT_NUM AS PRID,
    p.ITEM_NUM,
    (SELECT b.ITEM_NAME FROM BRAND_ITEM b WHERE b.ITEM_NUM = 
       (SELECT b1.REF_NUM FROM BRAND_ITEM b1 WHERE b1.ITEM_NUM =p.ITEM_NUM)) AS 브랜드명,
    (SELECT b2.ITEM_NAME FROM BRAND_ITEM b2 WHERE b2.ITEM_NUM = p.ITEM_NUM) AS 품목명,
    p.PROPERTIES_NUM ,
    (SELECT c.COLOR FROM PRODUCT_PROPERTIES c WHERE c.PROPERTIES_NUM = 
       (SELECT c1.REF_NUM FROM PRODUCT_PROPERTIES c1 WHERE c1.PROPERTIES_NUM = p.PROPERTIES_NUM)) AS 색상,
    (SELECT c3.COLOR FROM PRODUCT_PROPERTIES c3 WHERE c3.PROPERTIES_NUM = p.PROPERTIES_NUM) AS 사이즈,
    p.COST AS 원가
FROM HEAD_OFFICE_PRODUCT p
WHERE (SELECT b2.ITEM_NAME FROM BRAND_ITEM b2 WHERE b2.BRAND_ITEM = p.BRAND_ITEM) = '포스';


SELECT 
    h.PRODUCT_NUM,
    b.ITEM_NAME,
    p.COLOR,
    h.COST,
    h.REG_DATE,
    h.PRODUCT_COUNT
FROM HEAD_OFFICE_PRODUCT h
JOIN BRAND_ITEM b ON h.ITEM_NUM = b.ITEM_NUM
JOIN PRODUCT_PROPERTIES p ON h.PROPERTIES_NUM = p.PROPERTIES_NUM
WHERE b.ITEM_NAME = '조던 범고래';

INSERT INTO HEAD_OFFICE_PRODUCT values(1,101,1001,300000,sysdate,0);
INSERT INTO HEAD_OFFICE_PRODUCT values(2,104,1002,350000,sysdate,0);
INSERT INTO HEAD_OFFICE_PRODUCT values(3,105,1003,330000,sysdate,0);
INSERT INTO HEAD_OFFICE_PRODUCT values(4,102,3001,340000,sysdate,0);
INSERT INTO HEAD_OFFICE_PRODUCT values(5,103,3001,340000,sysdate,0);

INSERT INTO PRODUCT_PROPERTIES values(101,'230',100);
INSERT INTO PRODUCT_PROPERTIES values(102,'240',100);
INSERT INTO PRODUCT_PROPERTIES values(103,'250',100);
INSERT INTO PRODUCT_PROPERTIES values(104,'260',100);
INSERT INTO PRODUCT_PROPERTIES values(105,'270',100);

SELECT 
    h.PRODUCT_NUM,
    bb.ITEM_NAME AS brand,
    b.ITEM_NAME,
    pp.COLOR AS color,
    p.COLOR AS prd_size,
    h.COST,
    h.REG_DATE,
    h.PRODUCT_COUNT
FROM HEAD_OFFICE_PRODUCT h
JOIN BRAND_ITEM b ON h.ITEM_NUM = b.ITEM_NUM
JOIN PRODUCT_PROPERTIES p ON h.PROPERTIES_NUM = p.PROPERTIES_NUM
LEFT JOIN PRODUCT_PROPERTIES pp ON p.REF_NUM = pp.PROPERTIES_NUM
LEFT JOIN BRAND_ITEM bb ON b.REF_NUM = bb.ITEM_NUM 
WHERE b.ITEM_NAME like '%'||''||'%';

